ROSTemplateFormatVersion: '2015-09-01'
Description:
  zh-cn: 创建嵌套堆栈资源，模板采用版本2015-09-01，设置超时时间为5分钟。
  en: Create nested stack resources with the template utilizing version 2015-09-01,
    setting a timeout of 5 minutes.
Resources:
  Stack:
    Type: ALIYUN::ROS::Stack
    Properties:
      TemplateBody:
        ROSTemplateFormatVersion: '2015-09-01'
      TimeoutMins: 5
