ROSTemplateFormatVersion: '2015-09-01'
Description:
  zh-cn: 创建Kubernetes集群，配置Ingress与Nginx，启用监控，自定义网络与安全设置。
  en: Create a Kubernetes cluster, configure Ingress with Nginx, enable monitoring,
    and customize network and security settings.
Parameters:
  AckName:
    Type: String
    Label:
      en: Cluster Name
      zh-cn: 集群名称
    Description:
      en: The name must be 1 to 63 characters in length and can contain letters, Chinese
        characters, digits, and hyphens (-).
      zh-cn: 名称为1~63个字符，可包含数字、汉字、英文字符或中划线（-）。
    AssociationProperty: AutoCompleteInput
    AssociationPropertyMetadata:
      Length: 5
      Prefix: cluster-for-nginx-
      CharacterClasses:
      - Class: lowercase
        min: 1
    AllowedPattern: ^[a-zA-Z0-9\u4e00-\u9fa5][-a-zA-Z0-9\u4e00-\u9fa5]{0,62}$
  ZoneId:
    Type: String
    Label:
      en: VSwitch Available Zone
      zh-cn: 可用区
    Description:
      en: If the available zone cannot be selected, please switch regions.
      zh-cn: 如果选择不到可用区，请切换地域。
    AssociationProperty: ALIYUN::VPC::Zone::ZoneId
  InstanceType:
    Type: String
    Label:
      en: Instance Type
      zh-cn: 节点规格
    Description:
      en: It is recommended to use a new generation of ecs instances. If the instance
        specification cannot be selected, please change the availability zone again.
      zh-cn: 建议使用新一代的 ecs 实例，如果选择不到实例规格，请重新更换可用区。
    AssociationProperty: ALIYUN::ECS::Instance::InstanceType
    AssociationPropertyMetadata:
      ZoneId: ${ZoneId}
      CreateACKClusterParams:
        NetworkPlugin: terway-eniip
  CommonName:
    Type: String
    Default: ack-for-nginx
Resources:
  EnableServiceSls:
    Type: ALIYUN::ROS::AutoEnableService
    Properties:
      ServiceName: SLS
  ModuleAcsCsProvision:
    Type: MODULE::ACS::CS::Provision
    Properties: {}
    DependsOn: EnableServiceSls
    Version: default
  Vpc:
    Type: ALIYUN::ECS::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      VpcName:
        Fn::Sub: ${CommonName}-vpc
  Vswitch:
    Type: ALIYUN::ECS::VSwitch
    Properties:
      ZoneId:
        Ref: ZoneId
      VpcId:
        Ref: Vpc
      CidrBlock: 192.168.0.0/24
      VSwitchName:
        Fn::Sub: ${CommonName}-${ZoneId}-vsw
  SecurityGroup:
    Type: ALIYUN::ECS::SecurityGroup
    Properties:
      VpcId:
        Ref: Vpc
      SecurityGroupName:
        Fn::Sub: ${CommonName}-sg
      SecurityGroupIngress:
      - PortRange: 22/22
        Priority: 1
        SourceCidrIp: 0.0.0.0/0
        IpProtocol: tcp
        NicType: internet
      SecurityGroupEgress:
      - PortRange: -1/-1
        Priority: 1
        IpProtocol: all
        DestCidrIp: 0.0.0.0/0
        NicType: internet
      - PortRange: -1/-1
        Priority: 1
        IpProtocol: all
        DestCidrIp: 0.0.0.0/0
        NicType: intranet
  RandomString:
    Type: ALIYUN::RandomString
    Properties:
      length: 10
      character_classes:
      - class: lowercase
        min: 1
      - class: uppercase
        min: 1
      - class: digits
        min: 1
      character_sequences:
      - sequence: '!@#$%^&*()_+-='
        min: 1
  Ack:
    Type: ALIYUN::CS::ManagedKubernetesCluster
    Properties:
      VpcId:
        Ref: Vpc
      VSwitchIds:
      - Ref: Vswitch
      PodVswitchIds:
      - Ref: Vswitch
      Name:
        Ref: AckName
      NumOfNodes: 3
      ClusterSpec: ack.pro.small
      ServiceCidr: 172.16.0.0/16
      Addons:
      - Name: security-inspector
      - Name: terway-eniip
        Config: '{"IPVlan":"false","NetworkPolicy":"false","ENITrunking":"false"}'
      - Name: csi-plugin
      - Name: csi-provisioner
      - Name: storage-operator
        Config: '{"CnfsOssEnable":"false","CnfsNasEnable":"false"}'
      - Name: logtail-ds
        Config: '{"IngressDashboardEnabled":"true"}'
      - Name: nginx-ingress-controller
        Config: '{"IngressSlbNetworkType":"internet","IngressSlbSpec":"slb.s2.small"}'
      - Name: ack-node-local-dns
      - Name: arms-prometheus
      - Name: ack-node-problem-detector
        Config: '{"sls_project_name":""}'
      EndpointPublicAccess: false
      SnatEntry: true
      LoadBalancerSpec: slb.s1.small
      IsEnterpriseSecurityGroup: false
      WorkerInstanceTypes:
      - Ref: InstanceType
      WorkerSystemDiskCategory: cloud_essd
      WorkerSystemDiskSize: 40
      LoginPassword:
        Fn::GetAtt:
        - RandomString
        - value
      Runtime:
        Name: containerd
        Version: 1.6.20
    DependsOn:
    - EnableServiceSls
    - ModuleAcsCsProvision
Metadata:
  ALIYUN::ROS::Interface:
    ParameterGroups:
    - Parameters:
      - AckName
      - ZoneId
      - InstanceType
    TemplateTags:
    - acs:technical-solution:ops-on-cloud:部署Nginx并通过Ingress暴露和监控服务-tech_solu_16
    Hidden:
    - CommonName
