ROSTemplateFormatVersion: '2015-09-01'
Description:
  zh-cn: 创建ECS部署集，含名称自定义与故障实例处理策略，默认保留停止状态实例。
  en: Create an ECS deployment set, including custom naming and failure handling policies
    for instances, with the default setting to retain stopped instances.
Parameters:
  DeploymentSetName:
    Type: String
    Default: mytest
  OnUnableToRedeployFailedInstance:
    Type: String
    Default: KeepStopped
Resources:
  DeploymentSet:
    Type: ALIYUN::ECS::DeploymentSet
    Properties:
      DeploymentSetName:
        Ref: DeploymentSetName
      OnUnableToRedeployFailedInstance:
        Ref: OnUnableToRedeployFailedInstance
Outputs:
  DeploymentSetId:
    Value:
      Fn::GetAtt:
      - DeploymentSet
      - DeploymentSetId
