ROSTemplateFormatVersion: '2015-09-01'
Description:
  zh-cn: 创建安全组规则，允许指定CIDR块内所有流量访问指定安全组。
  en: Create a security group rule to allow all traffic from a specified CIDR block
    to access a designated security group.
Parameters:
  SecurityGroupId:
    Type: String
    Description: SecurityGroup Id
  SourceCidrIp:
    Type: String
    Description: SourceCidr Ip
Resources:
  SgIngress:
    Type: ALIYUN::ECS::SecurityGroupIngress
    Properties:
      SecurityGroupId:
        Ref: SecurityGroupId
      IpProtocol: all
      PortRange: -1/-1
      NicType: intranet
      SourceCidrIp:
        Ref: SourceCidrIp
