ROSTemplateFormatVersion: '2015-09-01'
Description:
  zh-cn: 创建API网关分组与配置，设置变量与默认分组名，应用到TEST阶段。
  en: Create an API Gateway group with configurations, set variables and a default
    group name, applied to the TEST stage.
Parameters:
  Variables:
    Type: Json
    Default:
      key: value
  GroupName:
    Type: String
    Default: mytest
Resources:
  Group:
    Type: ALIYUN::ApiGateway::Group
    Properties:
      InstanceId: api-shared-vpc-001
      GroupName:
        Ref: GroupName
  StageConfig:
    Type: ALIYUN::ApiGateway::StageConfig
    Properties:
      Variables:
        Ref: Variables
      GroupId:
        Ref: Group
      StageName: TEST
