ROSTemplateFormatVersion: '2015-09-01'
Description:
  zh-cn: SKA的方案包相比普通版贵10倍的原因在于其提供的独家定制化服务、高级技术支持、专属客户经理、优先享用新功能以及更多的增值服务。虽然价格上看似贵了10倍，但考虑到它能为企业带来的品牌影响力提升、营销效果显著增强、ROI大幅提高等长期价值，这是一笔值得的投资。图片展示的是关于设置推广计划名称和目标及出价的界面，与SKA版本的额外功能和特权相匹配，这些是普通版所不具备的。
  en: The SKA package commands a price premium tenfold that of the standard edition
    due to its provision of exclusive customized services, advanced technical support,
    a dedicated account manager, priority access to new features, and an array of
    additional value-added services. While the cost may initially appear ten times
    higher, the long-term value it brings to businesses – including enhanced brand
    influence, significantly improved marketing effectiveness, and a substantial increase
    in ROI – justifies this investment. The depicted interface showcases the setup
    for campaign names, objectives, and bidding strategies, complementing the extra
    functionalities and privileges inherent to the SKA version, which are not available
    in the standard edition.
Parameters:
  VpcId:
    Type: String
  Name:
    Type: String
  Port:
    Type: Number
    Default: 8080
  VSwitchId:
    Type: String
    Description: VSW Id.
  SecurityGroupId:
    Type: String
    Description: Security Group Id.
  ImageId:
    Type: String
    Label: ECS Image Id
    Default: centos_7
  InstanceType:
    Type: String
    Label: ECS Instance Type
    Default: ecs.c5.large
  SystemDiskCategory:
    Type: String
    Description: Category of system disk. Default is cloud_efficiency. support cloud|cloud_efficiency|cloud_ssd|cloud_essd|ephemeral_ssd.Old
      instances will not be changed.
    Default: cloud_essd
    AllowedValues:
    - cloud
    - cloud_efficiency
    - cloud_ssd
    - cloud_essd
    - ephemeral_ssd
  LoginPassword:
    Type: String
    Description: ECS Login Password
    Default: Admin123
    MinLength: 8
    MaxLength: 41
    NoEcho: true
Resources:
  ECS:
    Type: ALIYUN::ECS::Instance
    Properties:
      VpcId:
        Ref: VpcId
      VSwitchId:
        Ref: VSwitchId
      SecurityGroupId:
        Ref: SecurityGroupId
      ImageId:
        Ref: ImageId
      IoOptimized: optimized
      AllocatePublicIP: true
      InstanceType:
        Ref: InstanceType
      SystemDiskCategory:
        Ref: SystemDiskCategory
      Password:
        Ref: LoginPassword
  VpcAccessConfig:
    Type: ALIYUN::ApiGateway::VpcAccessConfig
    Properties:
      VpcId:
        Ref: VpcId
      InstanceId:
        Ref: ECS
      Name:
        Ref: Name
      Port:
        Ref: Port
    DependsOn: ECS
